events { 
    worker_connections 1024; 
}

http {
    # Importante para que el navegador entienda el CSS y JS del frontend
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # 1. SERVIR EL FRONTEND (Archivos estáticos HTML/JS)
        # Cuando entres a http://localhost/ verás tu página
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # 2. PROXY PARA MICROSERVICIOS
        location /users/ { 
            proxy_pass http://ms-users:3000/; 
        }

        location /inventory/ { 
            proxy_pass http://ms-inventory:3000/; 
        }

        location /reports/ { 
            proxy_pass http://ms-reports:3000/; 
        }
    }
}