events { worker_connections 1024; }
http {
    server {
        listen 80;
        location /users/ { proxy_pass http://ms-users:3000/; }
        location /inventory/ { proxy_pass http://ms-inventory:3000/; }
        location /reports/ { proxy_pass http://ms-reports:3000/; }
    }
}
