server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/users/ { 
        proxy_pass http://ms-users:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    

    location /api/inventory/ { 
        proxy_pass http://ms-inventory:3000/; 
        proxy_set_header Host $host;
    }

    location /api/reports/ {
    proxy_pass http://ms-reports:3000/; 
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

}